FROM php:8.0-fpm-alpine

RUN apk update \
    && apk add  --no-cache git mysql-client curl libmcrypt libmcrypt-dev openssh-client icu-dev \
    libxml2-dev libzip-dev freetype-dev libpng-dev libjpeg-turbo-dev g++ make autoconf curl-dev openssl-dev \
    && docker-php-source extract \
    && pecl install xdebug \
    && pecl install mongodb \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-enable mongodb \
    && docker-php-ext-install pdo_mysql intl zip \
    && docker-php-source delete \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && rm -rf /tmp/*

RUN apk add gnu-libiconv --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted

ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php

CMD ["php-fpm", "-F"]

WORKDIR /var/www/app

EXPOSE 9003
